const Parameter = Object.freeze({
    BASEMAP: 'basemap',
    NONE_BASEMAP: 'none',
    ADD_LAYER: 'add-layer',
    GEOJSON_FILE_URL: 'geojson',
    ZOOM: 'zoom',
    CLUSTER: 'cluster',
    DISTANCE: 'distance',
    HEATMAP: 'heatmap',
    HEATMAP_RADIUS: 'radius',
    THEMATIC_RATE: 'rate',
    HEATMAP_BLUR: 'blur',
    THEMATIC: 'thematic',
    THEMATIC_LABEL: 'label',
    COLOR1: 'color1',
    COLOR2: 'color2',
    ALPHA: 'alpha',
    TITLE: 'title',
    TITLE_COLOR: 'title-color',
    TITLE_SIZE: 'title-size',
    LOAD_TYPE: 'load-type',
    INC_LOAD_TYPE: 'inc',
    ALL_LOAD_TYPE: 'all',
    LOAD_BLOCK_INC: 'inc',
    SLD_FILE_URL: 'sld',
    SLD_LAYER_NAME: 'sld-layer',
    LEGEND: 'legend',
    LEGEND_VERTICAL: 'v',
    LEGEND_HORIZONTAL: 'h',
    LEGEND_COLOR_WIDTH: 'legend-color-width',
    LEGEND_HEADER: 'legend-header',
    LEGEND_FOOTER: 'legend-footer',
    LEGEND_ITEM_COUNT: 'legend-item-count',
    LEGEND_LAYER_ZOOM: 'legend-layer-zoom',
    LEGEND_LAYER_VISIBILITY: 'legend-layer-visibility',
    OVERVIEW: 'overview',
    OVERVIEW_HEIGHT: 'overview-height',
    OVERVIEW_WIDTHT: 'overview-width',
    ATTRIBUTE_NO_NULL: 'attribute-no-null',
    LEGEND_COLORWIDTH_RATE: 'legend-colorwidth-rate',
    STROKE_COLOR: 'stroke-color',
    STROKE_WIDTH: 'stroke-width',
});

export default Parameter;