import './ui/MainTemplate';
import { SelectTool } from './ogv/tool/SelectTool';
import { UrlFileLoader } from './ogv/loader/UrlFileLoader';
import { AddLayerTool } from './ogv/tool/AddLayerTool';
import { MapSetting } from './ogv/map/MapSetting';
import { TitleMapTool } from './ogv/tool/TitleMapTool';
import { AddBasemapTool } from './ogv/tool/AddBasemapTool';
import { OverviewTool } from './ogv/tool/OverviewTool';
import { FullScreenTool } from './ogv/tool/FullScreenTool';
import { MapScreenshotTool } from './ogv/tool/MapScreenshotTool';
import { HTMLWidget } from './ui/HTMLWidget';

const mapSetting = new MapSetting();
const setting = mapSetting.getSetting();
new FullScreenTool(setting);
new AddBasemapTool(setting);
new OverviewTool(setting);
new TitleMapTool(setting);
new SelectTool(setting);
new AddLayerTool(mapSetting);
new MapScreenshotTool(mapSetting);
new UrlFileLoader(mapSetting).load();
// new HTMLWidget();